apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: provision-psi-cluster-and-setup-p12n-build
spec:
  params:
  - name: OPENSHIFT_INSTALLER_IMAGE
    type: string
    description: openshift installer image
  - name: OPENSHIFT_INSTALL_OS_IMAGE_OVERRIDE
    type: string
    description: openshift installer os image
  - name: CLUSTER_NAME
    type: string
    description: Cluster Name  
  - name: REPLICAS
    type: string
    description: How many replicas for the master and worker node
  - name: OPERATOR_ENVIRONMENT
    type: string
    description: Specify p12n operator environment (stage, pre-stage, prod)
  - name: CSV_VERSION
    type: string
    description: Sepcify operator CSV version (1.1.1, 1.2.0)
  workspaces:
  - name: install-dir
  - name: aws-secrets
  - name: psi-secrets
  - name: p12n-git
  - name: plumbing-git
  tasks:
  - name: provision-cluster-psi
    taskRef:
      name: provision-cluster-psi
    workspaces:
    - name: install-dir
      workspace: install-dir
    - name: aws-secrets
      workspace: aws-secrets
    - name: psi-secrets
      workspace: psi-secrets
    params:
    - name: CLUSTER_NAME
      value: $(params.CLUSTER_NAME)
    - name: REPLICAS
      value: $(params.REPLICAS)
    - name: OPENSHIFT_INSTALLER_IMAGE
      value: $(params.OPENSHIFT_INSTALLER_IMAGE)
    - name: OPENSHIFT_INSTALL_OS_IMAGE_OVERRIDE
      value: $(params.OPENSHIFT_INSTALL_OS_IMAGE_OVERRIDE)
  - name: clone-plumbing-git
    taskRef:
      name: git-clone
      kind: ClusterTask
    runAfter:
      - provision-cluster-psi  
    params:
      - name: url
        value: https://gitlab.cee.redhat.com/tekton/plumbing.git
      - name: deleteExisting
        value: "true"
      - name: sslVerify
        value: "false"
    workspaces:
    - name: output
      workspace: plumbing-git
  - name: setup-testing-accounts
    taskRef:
      name: setup-testing-accounts
    runAfter:
    - clone-plumbing-git
    params:
      - name: CLUSTER_NAME
        value: $(params.CLUSTER_NAME)
    workspaces:
    - name: install-dir
      workspace: install-dir
    - name: plumbing-git
      workspace: plumbing-git    
  - name: clone-p12n-git
    conditions:
    - conditionRef: check-for-operator-environment
      params:
        - name: OPERATOR_ENVIRONMENT
          value: $(params.OPERATOR_ENVIRONMENT)
    taskRef:
      name: git-clone
      kind: ClusterTask
    runAfter:
      - provision-cluster-psi  
    params:
      - name: url
        value: https://gitlab.cee.redhat.com/tekton/productize-pipelines.git
      - name: deleteExisting
        value: "true"
      - name: sslVerify
        value: "false"
      - name: revision
        value: master
    workspaces:
    - name: output
      workspace: p12n-git
  - name: setup-p12n-operator
    taskRef:
      name: setup-p12n-operator
    runAfter:
      - clone-p12n-git
    params:
      - name: CLUSTER_NAME
        value: $(params.CLUSTER_NAME)
      - name: OPERATOR_ENVIRONMENT
        value: $(params.OPERATOR_ENVIRONMENT)
      - name: CSV_VERSION
        value: $(params.CSV_VERSION)    
    workspaces:
      - name: install-dir
        workspace: install-dir
      - name: p12n-git
        workspace: p12n-git  
