apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: flexy-install-
spec:
  pipelineRef:
    name: flexy-install
  timeout: 3h
  params:
  - name: CLUSTER_NAME
    value: test46
  - name: LAUNCHER_VARS
    value: >-
      {
      "installer_payload_image":"quay.io/openshift-release-dev/ocp-release:4.6.5-x86_64",
      "num_workers": 2
      }
  - name: TEMPLATE
    value: private-templates/functionality-testing/aos-4_6/ipi-on-osp/versioned-installer
  workspaces:
  - name: flexy-output
    emptyDir: {}
  - name: flexy-secrets
    secret:
      secretName: flexy
  - name: install-dir
    persistentVolumeClaim:
      claimName: install-dir
  - name: plumbing-git
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
