apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: openshift-pipelines-upgrade-tests-
spec:
  pipelineRef:
    name: openshift-pipelines-upgrade-tests
  timeout: 3h
  params:
  - name: CLUSTER_NAME
    value: test46
  - name: LAUNCHER_VARS
    value: >-
      {
      "num_workers":2
      }
  - name: OPENSHIFT_VERSION
    value: stable-4.5
  - name: TEMPLATE
    value: private-templates/functionality-testing/aos-4_5/ipi-on-osp/versioned-installer
  - name: TUTORIAL_BRANCH_REVISION
    value: release-tech-preview-2
  - name: RELEASE-TESTS-IMAGE  
    value: quay.io/praveen4g0/release-tests:v1.2.0
  - name: PREVIOUS_CHANNEL
    value: "ocp-4.6"
  - name: CURRENT_CHANNEL
    value: "preview"
  - name: UPGRADE_CLUSTER
    value: "false"
  - name: UPGRADE_OCP_IMAGE
    value: http://quay.io/openshift-release-dev/ocp-release:4.6.6-x86_64
  workspaces:
  - name: flexy-output
    emptyDir: {}
  - name: flexy-secrets
    secret:
      secretName: flexy
  - name: install-dir
    persistentVolumeClaim:
      claimName: install-dir
  - name: git
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
