apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: provision-psi-cluster-and-setup-p12n-operator-
spec:
  pipelineRef:
    name: provision-psi-cluster-and-setup-p12n-build
  timeout: 1h
  params:
  - name: OPENSHIFT_INSTALLER_IMAGE
    value: quay.io/praveen4g0/release-tests-bootstrap-image:v1.2.0
  - name: OPENSHIFT_INSTALL_OS_IMAGE_OVERRIDE
    value: ""
  - name: CLUSTER_NAME
    value: pipelines-ci
  - name: REPLICAS
    value: "2"
  - name: OPERATOR_ENVIRONMENT
    value: pre-stage
  - name: INDEX
    value: "28723"
  workspaces:
  - name: install-dir
    persistentVolumeClaim:
      claimName: install-dir
  - name: plumbing-git
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi          
  - name: aws-secrets
    secret:
      secretName: aws
  - name: psi-secrets
    secret:
      secretName: psi