apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: setup-testing-accounts
spec:
  workspaces:
    - name: install-dir
      mountPath: "/install-dir"
      readOnly: true
    - name: plumbing-git
      mountPath: "/plumbing"
  params:
    - name: CLUSTER_NAME
      type: string
      description: cluster name
  steps:
    - name: setup-testing-accounts
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      workingDir: "/plumbing"
      script: |
          #!/usr/bin/env bash
          set -e -u -o pipefail
          oc login -u kubeadmin -p $(cat $(workspaces.install-dir.path)/$(params.CLUSTER_NAME)/auth/kubeadmin-password) $(cat $(workspaces.install-dir.path)/$(params.CLUSTER_NAME)/auth/api-url) --insecure-skip-tls-verify=true

          config/auth/01-test-auth.sh
          # Add cluster roles & rolebindings to all test users
          oc apply -f config/roles/user-roles-to-run-release-tests.yaml