apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: subscribe-to-pipelines-operator
spec:
  workspaces:
    - name: install-dir
      mountPath: "/install-dir"
      readOnly: true
    - name: plumbing-git
      mountPath: "/plumbing"
  params:
    - name: CLUSTER_NAME
      type: string
      description: cluster name
    - name: CHANNEL
      description: Place-holder to to provide subscription CHANNEL
      type: string
  steps:
    - name: subscribe-to-operator
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      workingDir: "/plumbing"
      script: |
          #!/usr/bin/env bash
          set -e -u -o pipefail
          export KUBECONFIG=$(workspaces.install-dir.path)/$(params.CLUSTER_NAME)/auth/kubeconfig
          
          config/operators/install-pipelines.sh $(params.CHANNEL)
