apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: subscribe-to-pipelines-operator
spec:
  workspaces:
    - name: install-dir
      mountPath: "/install-dir"
      readOnly: true
    - name: configmap
    - name: plumbing-git
      mountPath: "/plumbing"
  params:
    - name: CLUSTER_NAME
      type: string
      description: cluster name
    - name: SUBDIR
      description: subdirectory where plumbing git repository was cloned
  steps:
    - name: subscribe-to-operator
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      workingDir: "/plumbing/$(params.SUBDIR)"
      script: |
          #!/usr/bin/env bash
          set -e -u -o pipefail
          export KUBECONFIG=$(workspaces.install-dir.path)/$(params.CLUSTER_NAME)/auth/kubeconfig

          config/operators/pipelines.sh
