apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: subscribe-to-pipelines-operator
spec:
  workspaces:
    - name: install-dir
      mountPath: "/tekton/home/"
      readOnly: true
    - name: configmap
  params:
    - name: CLUSTER_NAME
      type: string
      description: cluster name
  steps:
    - name: subscribe-to-operator
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      workingDir: $(workspaces.install-dir.path)
      script: |
          #!/usr/bin/env bash
          set -e -u -o pipefail
          export KUBECONFIG=cluster/$(params.CLUSTER_NAME)/auth/kubeconfig

          echo -n "Subscribing to openshift pipelines operator...."
          # subscribe to pipelines operator
          oc apply -f $(workspaces.configmap.path)/subscription.yaml
          echo -n " Done."