apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: uninstall-pipelines-operator
spec:
  workspaces:
    - name: install-dir
      mountPath: "/tekton/home/"
      readOnly: true
    - name: plumbing-git
      mountPath: "/plumbing"  
  params:
    - name: CLUSTER_NAME
      type: string
      description: cluster name
    - name: CHANNEL
      description: Place-holder to to provide subscription CHANNEL
      type: string
  steps:
    - name: uninstall-operator
      image: quay.io/openshift/origin-cli:latest
      workingDir: "/plumbing"
      script: |
          #!/usr/bin/env bash
          set -e -u -o pipefail
          export KUBECONFIG=$(workspaces.install-dir.path)/$(params.CLUSTER_NAME)/auth/kubeconfig

          config/operators/uninstall-pipelines.sh $(params.CHANNEL)