apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: provision-psi-cluster
spec:
  params:
  - name: OPENSHIFT_INSTALLER_IMAGE
    type: string
    description: openshift installer image
  - name: OPENSHIFT_INSTALL_OS_IMAGE_OVERRIDE
    type: string
    description: openshift installer os image
  - name: CLUSTER_NAME
    type: string
    description: Cluster Name
  - name: REPLICAS
    type: string
    description: How many replicas for the master and worker node
  workspaces:
  - name: install-dir
  - name: aws-secrets
  - name: psi-secrets
  - name: plumbing-git
  tasks:
  - name: provision-cluster-psi
    taskRef:
      name: provision-cluster-psi
    workspaces:
    - name: install-dir
      workspace: install-dir
    - name: aws-secrets
      workspace: aws-secrets
    - name: psi-secrets
      workspace: psi-secrets
    params:
    - name: CLUSTER_NAME
      value: $(params.CLUSTER_NAME)
    - name: REPLICAS
      value: $(params.REPLICAS)
    - name: OPENSHIFT_INSTALLER_IMAGE
      value: $(params.OPENSHIFT_INSTALLER_IMAGE)
    - name: OPENSHIFT_INSTALL_OS_IMAGE_OVERRIDE
      value: $(params.OPENSHIFT_INSTALL_OS_IMAGE_OVERRIDE)
  - name: clone-plumbing-git
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
      - name: url
        value: https://gitlab.cee.redhat.com/tekton/plumbing.git
      - name: deleteExisting
        value: "true"
      - name: sslVerify
        value: "false"
      - name: subdirectory
        value: e2e-psi-ocp
    workspaces:
    - name: output
      workspace: plumbing-git
  - name: setup-testing-accounts
    taskRef:
      name: setup-testing-accounts
    runAfter:
    - clone-plumbing-git
    - provision-cluster-psi
    params:
      - name: CLUSTER_NAME
        value: $(params.CLUSTER_NAME)
      - name: SUBDIR
        value: e2e-psi-ocp
    workspaces:
    - name: install-dir
      workspace: install-dir
    - name: plumbing-git
      workspace: plumbing-git