apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: release-tests-crc
spec:
  params:
  - name: CLUSTER_NAME
    description: Cluster name
  - name: OPERATOR-ENV
    description: OpenShift Pipelines operator environment
  - name: RELEASE-TESTS-IMAGE
    description: release-tests latest image
  - name: UPLOADER-HOST
    description: To upload reports & logs to uploader hosts
  - name: CRC_BUNDLE
    description: The system bundle used for deployment of the OpenShift cluster
  - name: SUBDIR
    description: subdirectory where plumbing git repository should be cloned
    default: e2e-crc
  workspaces:
  - name: install-dir
  - name: cnv-cluster-secrets
  - name: configmap
  - name: plumbing-git
  tasks:
  - name: provision-crc-cluster
    taskRef:
      name: provision-crc-cluster
    params:
    - name: CLUSTER_NAME
      value: $(params.CLUSTER_NAME)
    - name: CRC_BUNDLE
      value: $(params.CRC_BUNDLE)  
    workspaces:
    - name: install-dir
      workspace: install-dir
    - name: cnv-cluster-secrets
      workspace: cnv-cluster-secrets
  - name: clone-plumbing-git
    taskRef:
      name: git-clone
      kind: ClusterTask
    runAfter:
    - provision-crc-cluster  
    params:
      - name: url
        value: https://gitlab.cee.redhat.com/tekton/plumbing.git
      - name: deleteExisting
        value: "true"
      - name: sslVerify
        value: "false"
      - name: subdirectory
        value: $(params.SUBDIR)
    workspaces:
    - name: output
      workspace: plumbing-git    
  - name: setup-testing-accounts
    taskRef:
      name: setup-testing-accounts
    runAfter:
    - clone-plumbing-git
    params:
      - name: CLUSTER_NAME
        value: $(params.CLUSTER_NAME)
      - name: SUBDIR
        value: $(params.SUBDIR)
    workspaces:
    - name: install-dir
      workspace: install-dir
    - name: plumbing-git
      workspace: plumbing-git
  - name: pipelines-operator-subscription
    taskRef:
      name: subscribe-to-pipelines-operator
    runAfter:
    - provision-crc-cluster
    params:
      - name: CLUSTER_NAME
        value: $(params.CLUSTER_NAME)
      - name: SUBDIR
        value: $(params.SUBDIR)
    workspaces:
    - name: install-dir
      workspace: install-dir
    - name: configmap
      workspace: configmap
    - name: plumbing-git
      workspace: plumbing-git
  - name: release-tests-pipelines
    taskRef:
      name: release-tests-pipelines
    retries: 1
    params:
    - name: OPERATOR-ENV
      value: $(params.OPERATOR-ENV)
    - name: IMAGE
      value: $(params.RELEASE-TESTS-IMAGE)
    - name: CLUSTER_NAME
      value: $(params.CLUSTER_NAME)
    - name: UPLOADER-HOST
      value: $(params.UPLOADER-HOST)
    runAfter:
    - pipelines-operator-subscription
    - setup-testing-accounts
    workspaces:
    - name: install-dir
      workspace: install-dir
  - name: release-tests-triggers
    taskRef:
      name: release-tests-triggers
    retries: 1
    params:
      - name: OPERATOR-ENV
        value: $(params.OPERATOR-ENV)
      - name: IMAGE
        value: $(params.RELEASE-TESTS-IMAGE)
      - name: CLUSTER_NAME
        value: $(params.CLUSTER_NAME)
      - name: UPLOADER-HOST
        value: $(params.UPLOADER-HOST)
    runAfter:
      - pipelines-operator-subscription
      - setup-testing-accounts
    workspaces:
      - name: install-dir
        workspace: install-dir
  - name: uninstall-pipelines-operator
    taskRef:
      name: uninstall-pipelines-operator
    runAfter:
    - release-tests-pipelines
    - release-tests-triggers
    params:
      - name: CLUSTER_NAME
        value: $(params.CLUSTER_NAME)
    workspaces:
    - name: install-dir
      workspace: install-dir
    - name: configmap
      workspace: configmap
  - name: destroy-crc-cluster
    taskRef:
        name: destroy-crc-cluster
    params:
      - name: CLUSTER_NAME
        value: $(params.CLUSTER_NAME)
    runAfter:
      - uninstall-pipelines-operator
    workspaces:
      - name: install-dir
        workspace: install-dir
