---
- name: Run release test on linux VM
  hosts: test-host
  tasks:
    - name: clone the release tests repository
      git:
        repo: https://github.com/openshift-pipelines/release-tests.git
        dest: ~/workspace/release-tests
        version: master
     - name: login to openshift cluster
       shell:
         cmd: oc login -u {{ lookup('env','OCP_USERNAME') }} -p {{ lookup('env','OCP_PASSWORD') }} {{ lookup('env','OCP_SERVER_ADDRESS') }} --insecure-skip-tls-verify=true
         chdir: /home/{{ ansible_user }}/workspace/release-tests
    - name: run cli tests
      shell:
        cmd: gauge run --env "test" --log-level=debug --verbose specs/cli/pipelines-e2e.spec
        chdir: /home/{{ ansible_user }}/workspace/release-tests
      register: output
      ignore_errors: True
    - debug: var=output.stdout_lines
