---
- name: Run upstream cli e2e tests on linux VM
  hosts: test-host
  tasks:
    - name: clone the upstream cli repo
      git:
        repo: https://github.com/tektoncd/cli.git
        dest: ~/workspace/cli
        version: master
    - name: build tkn binaries from code
      shell:
        cmd: go build -o tkn github.com/tektoncd/cli/cmd/tkn
        chdir: ~/workspace/cli
    - name: login to openshift cluster
      shell:
        cmd: oc login -u {{ lookup('env','OCP_USERNAME') }} -p {{ lookup('env','OCP_PASSWORD') }} {{ lookup('env','OCP_SERVER_ADDRESS') }} --insecure-skip-tls-verify=true
    - name: run cli e2e tests
      shell:
        cmd: export TEST_CLIENT_BINARY=/home/{{ ansible_user }}/workspace/cli/tkn; go test -v -count=1 -tags=e2e -timeout=20m ./test/e2e/...
        chdir: ~/workspace/cli
      register: output
      ignore_errors: True
    - debug: var=output.stdout_lines
 
