apiVersion: v1
kind: Secret
metadata:
  name: flexy
type: Opaque
data:
  psi-pipelines-shared.pem: $SSH_PRIVATE_KEY
stringData:
  credentials: |-
    aws_access_key_id = $AWS_ACCESS_KEY_ID
    aws_secret_access_key = $AWS_SECRET_ACCESS_KEY
  aws-config.yaml: |-
    services:
      AWS-CI:
        awscred: credentials
        host_opts:
          user: root
          class: SSHAccessibleHost
          # AWS EC2 private key
          # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html
          # Note: You also need to put the appropriate public key into config/keys
          ssh_private_key: psi-pipelines-shared.pem
        config_opts:
          region: us-east-2
        # Route53 domain
        # https://github.com/openshift/installer/blob/master/docs/user/aws/route53.md
        install_base_domain: tekton.codereadyqe.com
        cloud_type: aws
  psi-config.yaml: |-
    services:
      openstack_upshift:
        tenant_name: "psi-pipelines"
        user: "$PSI_CLOUD_USERNAME"
        password: "$PSI_CLOUD_PASSWORD"
        domain: { name: "redhat.com" }
        url: "https://rhos-d.infra.prod.upshift.rdu2.redhat.com:13000/v3/auth/tokens"
        image: "irrelevant"
        cloud_type: openstack
        fix_hostnames: true
        floating_ip_network: false
      dyndns:
        user_name: "$DYNDNS_USERNAME"
        password: "$DYNDNS_PASSWORD"
        customer_name: redhat
        zone: fw.rhcloud.com
        retries: 2
        domain_suffix: fw.rhcloud.com
        end_point: "https://api2.dynect.net"
  psi-pipelines-shared.pub: |-
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQFU+8vJTYwiDweqp5ONtZY1apciwlfnHLRS2aTFuIVGChaet3BBm51yZwd4apL7pJs98zR9loT7tP6UipjZLTSqUJZmhz+nQ+TNWl298G43F6JpgfQY5ETc+48zd/yfBK8E1MY0uX7//dsTsZRwwcx6kLy5b2BsfL8POvGXXWZ0v8KkS3D3jdg1973N+dvZtbkvTcqQvgrzRTWNnL6yHlx4fyIKzcZDnp2g1+U5S5huG9QDwt+oYidb7xsGMJkr6K8HWoI3VjfVenMVWGxQpgJ7zTLkkedITsel/1Jr2qtFygAQIsFPLPvV0keMQJohhEr3ydVtdoUmMim1dy+/Pb
  ENVIRONMENT: |
    REG_QUAY_USER=$QUAY_IO_USERNAME
    REG_QUAY_PASSWORD=$QUAY_IO_PASSWORD
    REG_CLOUD_USER=$QUAY_IO_USERNAME
    REG_CLOUD_PASSWORD=$QUAY_IO_PASSWORD

    REG_CONNECT_USER=$REGISTRY_RH_IO_USERNAME
    REG_CONNECT_PASSWORD=$REGISTRY_RH_IO_PASSWORD
    REG_REDHAT_USER=$REGISTRY_RH_IO_USERNAME
    REG_REDHAT_PASSWORD=$REGISTRY_RH_IO_PASSWORD